### ISSUE TITLE
Issue in uploading images

### ISSUE THREAD

**Issue by Neerajkashyap** [gulliverbms/django_grapesjs#2]
@gulliverbms Hi, I am facing problem while uploading images using browse button. The button is not clickable for some reason. So I was wondering if I’m missing anything?

**Comment by gulliverbms** [comment]
@Neerajkashyap Hi. Did you use the standard configuration? Are there any errors in the browser console?
At the moment there is no support for the local image store. Therefore, it is impossible to add an image from your local machine. In the current solution, you need to specify a link to remote hosting. (if I understand you correctly)
![imag](https://user-images.githubusercontent.com/39886575/41619237-26379f8c-740e-11e8-8bcf-dbd385ed9a46.png)
PS: This will be fixed in the future

**Comment by Neerajkashyap** [comment]
Thanks for your help. I am facing another issue, the editor is taking a lot of time to load. What could be the possible reasons for this ?

**Comment by Neerajkashyap** [comment]
Thanks for your help.
